### Criar Cliente
POST http://localhost:5021/api/clientes
Content-Type: application/json

{
  "nome": "Carlos Correa",
  "email": "carlos@gmail.com"
}

###

### Listar Clientes
GET http://localhost:5021/api/clientes

###

### Buscar Cliente por ID
GET http://localhost:5021/api/clientes/{{clienteId}}

###

### Atualizar Cliente
PUT http://localhost:5021/api/clientes/695d7c28ae76d6dd525a4953
Content-Type: application/json

{
  "nome": "Carlos Correa",
  "email": "carlos.correa@gmail.com"
}

###

### Deletar Cliente
DELETE http://localhost:5021/api/clientes/695d82487301ef8f072475de

###

### Criar Pedido
POST http://localhost:5021/api/pedidos
Content-Type: application/json

{
  "clienteId": "{{clienteId}}",
  "itens": [
    {
      "nome": "Notebook Dell",
      "preco": 2500.00,
      "quantidade": 1
    },
    {
      "nome": "Mouse Wireless",
      "preco": 50.00,
      "quantidade": 2
    }
  ]
}

###

### Listar Pedidos
GET http://localhost:5021/api/pedidos

###

### Buscar Pedido por ID
GET http://localhost:5021/api/pedidos/{{pedidoId}}

###

### Listar Pedidos de um Cliente
GET http://localhost:5021/api/clientes/{{clienteId}}/pedidos

###

### Informações da API
GET http://localhost:5021/api/info

###

### Swagger UI
GET http://localhost:5021
