version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: aula07-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db

  # Redis
  redis:
    image: redis:7.2-alpine
    container_name: aula07-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass password123
    volumes:
      - redis_data:/data

  # DynamoDB Local
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: aula07-dynamodb
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

volumes:
  mongodb_data:
  redis_data:
