version: '3.8'

services:
  # MongoDB Replica Set
  mongodb-primary:
    image: mongo:7.0
    container_name: aula03-mongodb-primary
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb_primary_data:/data/db

  mongodb-secondary:
    image: mongo:7.0
    container_name: aula03-mongodb-secondary
    restart: unless-stopped
    ports:
      - "27018:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb_secondary_data:/data/db

volumes:
  mongodb_primary_data:
  mongodb_secondary_data:
